const fs = require('fs-extra');
const concat = require('concat');

(async function build() {
    const files = [
        './dist/test-web-cmp/runtime-es5.js',
        './dist/test-web-cmp/polyfills-es5.js',
        './dist/test-web-cmp/scripts.js',
        './dist/test-web-cmp/main-es5.js'
    ]; // files generated by build

    await fs.ensureDir('test'); // create folder 'test' if it doesn't exist
    await concat(files, 'test/test-web-cmp.js'); // merge files into one which will be exported
})();

